### ISSUE TITLE
Not all terminals are recognized

### ISSUE THREAD

**Issue by GitMensch** [DmLam/GrammarEdit#5]
Using a big grammar sample like https://raw.githubusercontent.com/fesch/Structorizer.Desktop/master/src/lu/fisch/structorizer/parsers/GnuCOBOL.grm some terminals are missing. I assume these are defined in a list that has a maximum size. Tokens defined in this sample until line 693 are recognized, the one that are defined in the next lines seem to be missing.

**Comment by DmLam** [comment]
Seems like we have here a problem with line comment on line 694
It is not parsed by engine and produces syntax error wich is not recoverable, therefore parsing stop here.

**Comment by GitMensch** [comment]
Interesting. The inline comment *should* be fine, shouldn't it? Does it work if the comment is changed to a block comment?

I *guess* fixing the engine would be possible, wouldn't it?
BTW: Which engine do you use? The current one is from "Beany" but this isn't listed at http://goldparser.org/engine/1/delphi/index.htm ?!?

**Comment by DmLam** [comment]
Yes, seems the engine I used has troubles with inline comment after something else on the line. I'll try to do something. Don't remember where I found the engine - too much time passed, but I think it was the official site.

**Comment by DmLam** [comment]
Fixed in https://github.com/DmLam/GrammarEdit/releases/tag/Version_1.3
