### ISSUE TITLE
gold is dead?

### ISSUE THREAD

**Issue by ghost** [DmLam/GrammarEdit#6]

**Comment by DmLam** [comment]
I don't know, but it looks like that. May be better to ask Devin Cook directly.

**Comment by ghost** [comment]
Do you think I recommend that I revive this project? consultant him only now, what is your point of view if I resurrect him?





Marcello Mello
Se7e Sistemas
Goiânia - GO




-----Mensagem Original-----
De: "Dmitry Lamdan" <notifications@github.com>
Para: DmLam/GrammarEdit <GrammarEdit@noreply.github.com>
Cc: "Marcello Mello" <marcelo@se7esistemas.com.br>, Author <author@noreply.github.com>
Data: 26/08/2018 03:17
Assunto: Re: [DmLam/GrammarEdit] gold is dead? (#6)


I don't know, but it looks like that. May be better to ask Devin Cook directly.

**Comment by DmLam** [comment]
What project do you talk about, sorry? GoldParser? Why do you need my opinion about it? If Devin has nothing about it - why don't try to ressurect it, I think many users would be grateful to you.

**Comment by ghost** [comment]
thank you
